cut_add_music(snd_Cutscene_Music,false);
cut_add_image(back_story_point_one,17.5 * room_speed,false);
cut_add_wait(0.5 * room_speed);
cut_add_text("The year is 2015",2.5 * room_speed,true);
cut_add_wait(1.5 * room_speed);
cut_add_text("It was done...",3 * room_speed,true);
cut_add_wait(room_speed);
cut_add_text("War broke out cascading into an out of control nuclear apocalypse",5 * room_speed,true);
cut_add_wait(room_speed);
cut_add_text("Civilization was destroyed",2.5 * room_speed,true);
cut_add_wait(0.5 * room_speed);
cut_add_image(back_story_point_two,15.5 * room_speed,false);
cut_add_wait(0.5 * room_speed);
cut_add_text("There was still hope",4 * room_speed,true);
cut_add_wait(2 * room_speed);
cut_add_text("A group of survivors banded together to rebuild society",5 * room_speed,true);
cut_add_wait(room_speed);
cut_add_text("Industrial Industries was born ...",3.5 * room_speed,true);
cut_add_wait(0.5 * room_speed);
cut_add_text("Yet one person was determined to stop them",4 * room_speed,true);
cut_add_wait(0.5 * room_speed);
cut_add_image(back_story_point_three,5 * room_speed,false);
cut_add_wait(0.25 * room_speed);
cut_add_text("His name?",3 * room_speed,true);
cut_add_vol_fade(0, 6 * room_speed);
cut_add_wait(2 * room_speed);
cut_add_text("Darius.",4 * room_speed,true);
