cut_add_music(snd_Credits_Music,false);
cut_add_image(back_fireproof_logo,120 * room_speed,false);
cut_add_text("Credits",3 * room_speed,true);
cut_add_wait(5 * room_speed);
cut_add_text("Developed By - Fireproof Games",10 * room_speed,true);
cut_add_wait(3 * room_speed);
cut_add_text("Programming - Matthew Turner",10 * room_speed,true);
cut_add_wait(3 * room_speed);
cut_add_text("Firefight - Brian Wright",10 * room_speed,true);
cut_add_wait(3 * room_speed);
cut_add_text("Most Art - Brian Wright",10 * room_speed,true);
cut_add_wait(3 * room_speed);
cut_add_text("Other Art - Matthew Turner, Ian Engebrecht",10 * room_speed,true);
cut_add_wait(3 * room_speed);
cut_add_text("Everything Else - The Internet",10 * room_speed,true);
cut_add_wait(3 * room_speed);
cut_add_text("Special Thanks To",10 * room_speed,true);
cut_add_wait(3 * room_speed);
cut_add_text("Darius Hines-Cross | "+'"'+"You're The Best"+'"'+" - Matthew Turner",10 * room_speed,true);
cut_add_wait(3 * room_speed);
cut_add_text("Everyone | "+'"'+"Thank You All For Making This Possible"+'"'+" - Fireproof Games",10 * room_speed,true);
cut_add_vol_fade(0,2 * room_speed);
cut_add_wait(2 * room_speed);
